apiVersion: apps/v1
kind: Deployment

metadata:
  name: app-deployment
  namespace: online-shop

spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: web-app
          image: anaslinux/my-app:latest
          ports:
           - containerPort: 80

